-- User preferences for automation
CREATE TABLE user_preferences (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  dietary_preferences TEXT[] DEFAULT '{}',
  health_goals TEXT[] DEFAULT '{}',
  allergies TEXT[] DEFAULT '{}',
  notifications_enabled BOOLEAN DEFAULT true,
  notification_times JSONB DEFAULT '{"breakfast": "07:00", "lunch": "12:00", "dinner": "18:00"}',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Daily meal plans generated by automation
CREATE TABLE daily_meal_plans (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  date DATE DEFAULT CURRENT_DATE,
  meal_plan JSONB,
  sent_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- User inventory for ingredient tracking
CREATE TABLE user_inventory (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  ingredient_name TEXT NOT NULL,
  quantity INTEGER DEFAULT 0,
  unit TEXT DEFAULT 'pieces',
  min_threshold INTEGER DEFAULT 2,
  last_updated TIMESTAMP DEFAULT NOW()
);

-- Health reminders log
CREATE TABLE health_reminders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  reminder_type TEXT NOT NULL,
  message TEXT NOT NULL,
  scheduled_for TIMESTAMP,
  sent_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- User feedback for AI learning
CREATE TABLE user_feedback (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  recipe_id INTEGER,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  feedback TEXT,
  cuisine_type TEXT,
  cooking_time INTEGER,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_meal_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_feedback ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view own preferences" ON user_preferences FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own preferences" ON user_preferences FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view own meal plans" ON daily_meal_plans FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can view own inventory" ON user_inventory FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can view own reminders" ON health_reminders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can add own feedback" ON user_feedback FOR ALL USING (auth.uid() = user_id);